"""Per-project ``.sil`` plant models.

Model management lives inside a project: every project owns its own list of
Silver plant models. A model is registered in one of two ways:

* **Path** -- an administrator/editor registers an absolute server-side
  ``.sil`` path (``add_path_model``). The file is opened in place, exactly like
  the legacy global model registry.
* **Bundle** -- the user uploads a ``host.dll`` + ``host.sbs`` pair through the
  web UI (``add_bundle_model``). The service stores both files in a per-project
  directory and generates a fresh ``.sil`` through the real Silver API: an empty
  configuration is created in memory (``LocalSilverNative(sil=None)``), the
  module line ``<dll> -S <sbs>`` is injected with ``add_module`` and the result
  is written with ``save()`` (see :meth:`app.runners.silver_runner.SilverRunner.
  generate_sil`). The dll and sbs sit next to the generated ``.sil`` so Silver
  resolves the (relative) module names against the model's own folder. When the
  mock runner is active (no license) a minimal text ``.sil`` is written instead.

Models are stored in the ``lm_project_models`` table (see
:class:`app.models.lanmatrix.ProjectModel`). For backward compatibility with
older single-model deployments, the ``effective_*`` helpers fall back to the
global admin registry (:mod:`.model_service`) when a project has no models of
its own.
"""

from __future__ import annotations

import datetime as _dt
import re
import shutil
from pathlib import Path
from typing import List, Optional

from werkzeug.datastructures import FileStorage

from ..extensions import db
from ..models import ProjectModel
from . import model_service


class ModelError(Exception):
    """Raised for invalid model registrations."""


# Characters unsafe as a single path segment / filename (mirrors run_layout).
_BAD_SEGMENT = re.compile(r'[<>:"/\\|?*\x00-\x1f]+')


def _safe_segment(name: str, fallback: str) -> str:
    token = _BAD_SEGMENT.sub("_", (name or "").strip()).strip(" .")
    return token or fallback


def _safe_filename(name: str, fallback: str) -> str:
    """A safe base filename that preserves the extension."""
    base = Path((name or "").replace("\\", "/")).name
    token = _BAD_SEGMENT.sub("_", base).strip(" .")
    return token or fallback


# --------------------------------------------------------------------------- #
# Low-level helpers
# --------------------------------------------------------------------------- #
def _query(project_id: int):
    return ProjectModel.query.filter_by(project_id=project_id)


def _models_root(config, project_id: int) -> Path:
    """Server directory that holds a project's uploaded model bundles."""
    return Path(config.MODEL_DIR) / f"project_{project_id}"


def _write_text_sil(sil_path: Path, dll_name: str, sbs_name: str) -> None:
    """Mock-backend fallback: write a minimal text ``.sil`` (no license).

    Used only when the real Silver backend is unavailable (``mock`` runner /
    machines without a license). The file is never loaded by a real Silver
    instance in that mode, so a plain single-module line is sufficient.
    """
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = (
        "# Auto-generated by Silver Test Platform (mock backend)\n"
        f"# {stamp}\n"
        f"{dll_name} -S {sbs_name}\n"
    )
    sil_path.write_text(content, encoding="utf-8")


def _generate_sil(config, sil_path: Path, dll_name: str, sbs_name: str) -> None:
    """Generate the bundle's ``.sil``.

    With the real Silver backend the file is produced through the Silver API
    (create an empty config, ``add_module('<dll> -S <sbs>')``, ``save()``) so
    it is a genuine, loadable Silver model. With the mock backend a minimal
    text ``.sil`` is written instead so model creation still works without a
    license.
    """
    backend = getattr(config, "RUNNER_BACKEND", "mock")
    if backend == "silver":
        from ..runners.silver_runner import RunnerError, SilverRunner
        try:
            SilverRunner().generate_sil(sil_path, dll_name, sbs_name, index=3)
        except RunnerError as exc:
            raise ModelError(f"\u751f\u6210 .sil \u5931\u8d25\uff1a{exc}") from exc
        except Exception as exc:  # noqa: BLE001 - surface a clean 400 to the UI
            raise ModelError(
                f"\u751f\u6210 .sil \u5931\u8d25\uff1a{type(exc).__name__}: {exc}") from exc
    else:
        _write_text_sil(sil_path, dll_name, sbs_name)


# --------------------------------------------------------------------------- #
# Per-project reads
# --------------------------------------------------------------------------- #
def list_models(project_id: int, include_path: bool = False) -> List[dict]:
    rows = _query(project_id).order_by(ProjectModel.id.asc()).all()
    return [r.to_dict(include_path=include_path) for r in rows]


def has_models(project_id: int) -> bool:
    return db.session.query(ProjectModel.id).filter_by(
        project_id=project_id).first() is not None


def get_model_path(project_id: int, name: str) -> Optional[Path]:
    if not name:
        return None
    row = _query(project_id).filter_by(name=name).first()
    if row is not None and row.sil_path:
        return Path(row.sil_path)
    return None


def default_model(project_id: int) -> Optional[dict]:
    row = _query(project_id).order_by(ProjectModel.id.asc()).first()
    return {"name": row.name} if row is not None else None


# --------------------------------------------------------------------------- #
# Effective reads (project models, falling back to the legacy global registry)
# --------------------------------------------------------------------------- #
def effective_models(project_id: int, include_path: bool = False) -> List[dict]:
    rows = list_models(project_id, include_path=include_path)
    if rows:
        return rows
    return model_service.list_models(include_path=include_path)


def effective_has(project_id: int) -> bool:
    return has_models(project_id) or model_service.has_models()


def effective_path(project_id: int, name: str) -> Optional[Path]:
    path = get_model_path(project_id, name)
    if path is not None:
        return path
    if not has_models(project_id):
        return model_service.get_model_path(name)
    return None


def effective_default(project_id: int) -> Optional[dict]:
    row = default_model(project_id)
    if row is not None:
        return row
    return model_service.default_model()


# --------------------------------------------------------------------------- #
# Writes
# --------------------------------------------------------------------------- #
def _validate_name(project_id: int, name: str) -> None:
    if _query(project_id).filter_by(name=name).first() is not None:
        raise ModelError(f"\u8be5\u9879\u76ee\u5df2\u5b58\u5728\u540d\u4e3a '{name}' \u7684\u6a21\u578b\u3002")


def add_path_model(project_id: int, name: str, path: str,
                   created_by: Optional[int] = None) -> dict:
    """Register a server-side ``.sil`` path for a project."""
    name = (name or "").strip()
    path = (path or "").strip().strip('"')
    if not path:
        raise ModelError("\u8bf7\u586b\u5199 .sil \u6587\u4ef6\u7684\u670d\u52a1\u5668\u7edd\u5bf9\u8def\u5f84\u3002")
    if not path.lower().endswith(".sil"):
        raise ModelError("\u8def\u5f84\u5fc5\u987b\u6307\u5411 Silver \u6a21\u578b\u6587\u4ef6 (*.sil)\u3002")
    if not name:
        name = Path(path).stem or Path(path).name
    _validate_name(project_id, name)
    row = ProjectModel(project_id=project_id, name=name, kind="path",
                       sil_path=str(Path(path)), created_by=created_by)
    db.session.add(row)
    db.session.commit()
    return row.to_dict(include_path=True)


def add_bundle_model(project_id: int, name: str, dll: FileStorage,
                     sbs: FileStorage, config,
                     created_by: Optional[int] = None) -> dict:
    """Store an uploaded ``dll`` + ``sbs`` pair and generate the ``.sil``.

    A per-project model directory is created; the dll and sbs are saved there
    and a fresh ``.sil`` is generated through the Silver API (an empty config
    with a single ``<dll> -S <sbs>`` module, then ``save()``). All three files
    sit in the same directory so Silver resolves the relative module names.
    """
    name = (name or "").strip()
    if dll is None or not dll.filename:
        raise ModelError("\u8bf7\u4e0a\u4f20 dll \u6587\u4ef6\u3002")
    if sbs is None or not sbs.filename:
        raise ModelError("\u8bf7\u4e0a\u4f20 sbs \u6587\u4ef6\u3002")

    dll_name = _safe_filename(dll.filename, "host.dll")
    sbs_name = _safe_filename(sbs.filename, "host.sbs")
    if not dll_name.lower().endswith(".dll"):
        raise ModelError("\u7b2c\u4e00\u4e2a\u6587\u4ef6\u5fc5\u987b\u662f .dll\u3002")
    if not sbs_name.lower().endswith(".sbs"):
        raise ModelError("\u7b2c\u4e8c\u4e2a\u6587\u4ef6\u5fc5\u987b\u662f .sbs\u3002")
    if not name:
        name = Path(dll_name).stem or "model"
    _validate_name(project_id, name)

    seg = _safe_segment(name, f"model_{Path(dll_name).stem}")
    model_dir = _models_root(config, project_id) / seg
    if model_dir.exists():
        shutil.rmtree(model_dir, ignore_errors=True)
    model_dir.mkdir(parents=True, exist_ok=True)

    try:
        dll.save(str(model_dir / dll_name))
        sbs.save(str(model_dir / sbs_name))
        sil_path = model_dir / f"{seg}.sil"
        _generate_sil(config, sil_path, dll_name, sbs_name)
    except Exception:  # noqa: BLE001 - clean up a half-written bundle
        shutil.rmtree(model_dir, ignore_errors=True)
        raise

    row = ProjectModel(project_id=project_id, name=name, kind="bundle",
                       sil_path=str(sil_path), bundle_dir=str(model_dir),
                       created_by=created_by)
    db.session.add(row)
    db.session.commit()
    return row.to_dict(include_path=True)


def remove_model(project_id: int, name: str) -> bool:
    """Remove a project model. Bundle files on disk are deleted too."""
    row = _query(project_id).filter_by(name=(name or "").strip()).first()
    if row is None:
        return False
    if row.kind == "bundle" and row.bundle_dir:
        shutil.rmtree(row.bundle_dir, ignore_errors=True)
    db.session.delete(row)
    db.session.commit()
    return True
