"""Per-project ``.sil`` plant models.

Model management lives inside a project: every project owns its own list of
Silver plant models. A model is registered in one of two ways:

* **Path** -- an administrator/editor registers an absolute server-side
  ``.sil`` path (``add_path_model``). The file is opened in place, exactly like
  the legacy global model registry.
* **Bundle** -- the user uploads a ``host.dll`` + ``host.sbs`` pair through the
  web UI (``add_bundle_model``). The service stores both files in a per-project
  directory and generates an *empty* ``.sil`` whose only module line is
  ``<dll> -S <sbs>``. The dll and sbs sit next to the generated ``.sil`` so
  Silver resolves the (relative) module names against the model's own folder.

Models are stored in the ``lm_project_models`` table (see
:class:`app.models.lanmatrix.ProjectModel`). For backward compatibility with
older single-model deployments, the ``effective_*`` helpers fall back to the
global admin registry (:mod:`.model_service`) when a project has no models of
its own.
"""

from __future__ import annotations

import datetime as _dt
import re
import shutil
from pathlib import Path
from typing import List, Optional

from werkzeug.datastructures import FileStorage

from ..extensions import db
from ..models import ProjectModel
from . import model_service


class ModelError(Exception):
    """Raised for invalid model registrations."""


# Characters unsafe as a single path segment / filename (mirrors run_layout).
_BAD_SEGMENT = re.compile(r'[<>:"/\\|?*\x00-\x1f]+')


def _safe_segment(name: str, fallback: str) -> str:
    token = _BAD_SEGMENT.sub("_", (name or "").strip()).strip(" .")
    return token or fallback


def _safe_filename(name: str, fallback: str) -> str:
    """A safe base filename that preserves the extension."""
    base = Path((name or "").replace("\\", "/")).name
    token = _BAD_SEGMENT.sub("_", base).strip(" .")
    return token or fallback


# --------------------------------------------------------------------------- #
# Low-level helpers
# --------------------------------------------------------------------------- #
def _query(project_id: int):
    return ProjectModel.query.filter_by(project_id=project_id)


def _models_root(config, project_id: int) -> Path:
    """Server directory that holds a project's uploaded model bundles."""
    return Path(config.MODEL_DIR) / f"project_{project_id}"


def _write_sil(sil_path: Path, dll_name: str, sbs_name: str) -> None:
    """Write an empty Silver config whose only module is ``<dll> -S <sbs>``.

    The dll and sbs are referenced by their bare filenames, so Silver resolves
    them against the ``.sil`` file's own directory (they are stored alongside).
    """
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    content = (
        "# Auto-generated by Silver Test Platform\n"
        f"# {stamp}\n"
        f"{dll_name} -S {sbs_name}\n"
    )
    sil_path.write_text(content, encoding="utf-8")


# --------------------------------------------------------------------------- #
# Per-project reads
# --------------------------------------------------------------------------- #
def list_models(project_id: int, include_path: bool = False) -> List[dict]:
    rows = _query(project_id).order_by(ProjectModel.id.asc()).all()
    return [r.to_dict(include_path=include_path) for r in rows]


def has_models(project_id: int) -> bool:
    return db.session.query(ProjectModel.id).filter_by(
        project_id=project_id).first() is not None


def get_model_path(project_id: int, name: str) -> Optional[Path]:
    if not name:
        return None
    row = _query(project_id).filter_by(name=name).first()
    if row is not None and row.sil_path:
        return Path(row.sil_path)
    return None


def default_model(project_id: int) -> Optional[dict]:
    row = _query(project_id).order_by(ProjectModel.id.asc()).first()
    return {"name": row.name} if row is not None else None


# --------------------------------------------------------------------------- #
# Effective reads (project models, falling back to the legacy global registry)
# --------------------------------------------------------------------------- #
def effective_models(project_id: int, include_path: bool = False) -> List[dict]:
    rows = list_models(project_id, include_path=include_path)
    if rows:
        return rows
    return model_service.list_models(include_path=include_path)


def effective_has(project_id: int) -> bool:
    return has_models(project_id) or model_service.has_models()


def effective_path(project_id: int, name: str) -> Optional[Path]:
    path = get_model_path(project_id, name)
    if path is not None:
        return path
    if not has_models(project_id):
        return model_service.get_model_path(name)
    return None


def effective_default(project_id: int) -> Optional[dict]:
    row = default_model(project_id)
    if row is not None:
        return row
    return model_service.default_model()


# --------------------------------------------------------------------------- #
# Writes
# --------------------------------------------------------------------------- #
def _validate_name(project_id: int, name: str) -> None:
    if _query(project_id).filter_by(name=name).first() is not None:
        raise ModelError(f"该项目已存在名为 '{name}' 的模型。")


def add_path_model(project_id: int, name: str, path: str,
                   created_by: Optional[int] = None) -> dict:
    """Register a server-side ``.sil`` path for a project."""
    name = (name or "").strip()
    path = (path or "").strip().strip('"')
    if not path:
        raise ModelError("请填写 .sil 文件的服务器绝对路径。")
    if not path.lower().endswith(".sil"):
        raise ModelError("路径必须指向 Silver 模型文件 (*.sil)。")
    if not name:
        name = Path(path).stem or Path(path).name
    _validate_name(project_id, name)
    row = ProjectModel(project_id=project_id, name=name, kind="path",
                       sil_path=str(Path(path)), created_by=created_by)
    db.session.add(row)
    db.session.commit()
    return row.to_dict(include_path=True)


def add_bundle_model(project_id: int, name: str, dll: FileStorage,
                     sbs: FileStorage, config,
                     created_by: Optional[int] = None) -> dict:
    """Store an uploaded ``dll`` + ``sbs`` pair and generate the ``.sil``.

    A per-project model directory is created; the dll and sbs are saved there
    and an empty ``.sil`` is generated whose only module line is
    ``<dll> -S <sbs>``. All three files sit in the same directory.
    """
    name = (name or "").strip()
    if dll is None or not dll.filename:
        raise ModelError("请上传 dll 文件。")
    if sbs is None or not sbs.filename:
        raise ModelError("请上传 sbs 文件。")

    dll_name = _safe_filename(dll.filename, "host.dll")
    sbs_name = _safe_filename(sbs.filename, "host.sbs")
    if not dll_name.lower().endswith(".dll"):
        raise ModelError("第一个文件必须是 .dll。")
    if not sbs_name.lower().endswith(".sbs"):
        raise ModelError("第二个文件必须是 .sbs。")
    if not name:
        name = Path(dll_name).stem or "model"
    _validate_name(project_id, name)

    seg = _safe_segment(name, f"model_{Path(dll_name).stem}")
    model_dir = _models_root(config, project_id) / seg
    if model_dir.exists():
        shutil.rmtree(model_dir, ignore_errors=True)
    model_dir.mkdir(parents=True, exist_ok=True)

    try:
        dll.save(str(model_dir / dll_name))
        sbs.save(str(model_dir / sbs_name))
        sil_path = model_dir / f"{seg}.sil"
        _write_sil(sil_path, dll_name, sbs_name)
    except Exception:  # noqa: BLE001 - clean up a half-written bundle
        shutil.rmtree(model_dir, ignore_errors=True)
        raise

    row = ProjectModel(project_id=project_id, name=name, kind="bundle",
                       sil_path=str(sil_path), bundle_dir=str(model_dir),
                       created_by=created_by)
    db.session.add(row)
    db.session.commit()
    return row.to_dict(include_path=True)


def remove_model(project_id: int, name: str) -> bool:
    """Remove a project model. Bundle files on disk are deleted too."""
    row = _query(project_id).filter_by(name=(name or "").strip()).first()
    if row is None:
        return False
    if row.kind == "bundle" and row.bundle_dir:
        shutil.rmtree(row.bundle_dir, ignore_errors=True)
    db.session.delete(row)
    db.session.commit()
    return True
